#include char/Makefile
include $(GOROOT)/src/Make.$(GOARCH)

TARG=prototype2

GOFILES=\
	eventqueue.go \
	keyman.go \
	elements.go \
	power.go \
	creature.go \
	combattant.go \
	arena.go \
	main.go \

CLEANFILES+=

include $(GOROOT)/src/Make.cmd
